### ISSUE TITLE
Can not able to compare and pull requests to update chinese translations

### ISSUE THREAD

**Issue by ilworkcn** [yesBad/pterodactyl-custom-translations#36]
As the title , i have uploaded the file to ubuntu pastebin for u to upload it. if u want. XD
the link is [Paste from iceling 10 June 2022 10:54 +0000](https://pastebin.ubuntu.com/p/HDr4qzSkSH/)

**Comment by yesBad** [comment]
Hmm, why are you unable to compare & pr?
