### ISSUE TITLE
Please support 1.9.1

### ISSUE THREAD

**Issue by iVampireSP** [yesBad/pterodactyl-custom-translations#39]
Hello, can you support 1.9.1? 🤗

**Comment by yesBad** [comment]
I don't currently have free-time as I have work. I'll try to do it when I have more free-time.

**Comment by yesBad** [comment]
Also I'd wait for 1.9.2 to come even if I would have free-time.

**Comment by KingTino104** [comment]
> Also I'd wait for 1.9.2 to come even if I would have free-time.

Its now 1.10.1

**Comment by yesBad** [comment]
> > Also I'd wait for 1.9.2 to come even if I would have free-time.
> 
> Its now 1.10.1

You say this like I'm not aware? 🤔

I'm sorry, haven't really had motivation nor free-time for this project.
